Portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from users import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('GamingPortfolio.urls')),
    path('',include('Titleratings.urls')),
    path('',include('pollster.urls')),
    path('',include('users.urls')),
    path('',include('UpcomingGames.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/<uidb64>/<token>/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),
    path('register/', views.register,name='register'),
    path('profile/', views.profile,name='profile'),
  
]

if settings.DEBUG: # new
    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pollster/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name='pollster'
urlpatterns = [
    
    
    path('polls/',views.index,name='index'),
    path('<int:question_id>',views.detail,name='detail'),
    path('<int:question_id>/results',views.results,name='results'),
    path('<int:question_id>/vote',views.vote,name='vote')
]

users/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('register/', views.register),
    
]

pollster/models.py
from django.db import models

class Question(models.Model):
    question = models.CharField(max_length=300)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question

class Choice(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text        

pollster/views.py
from django.shortcuts import render,get_object_or_404
from .models import *
from django.template import loader
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse

def index(request):
    latest_question_list = Question.objects.order_by('pub_date')
    context = {
        'latest_question_list' : latest_question_list
    }
    return render(request,'pollster/index.html',context)

def detail(request,question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request,'pollster/detail.html',{'question': question})

def results(request,question_id):
    question = get_object_or_404(Question,pk=question_id)
    return render(request,'pollster/result.html',{'question': question})    

def vote(request,question_id):
    question = get_object_or_404(Question,pk=question_id)    
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError,Choice.DoesNotExist):
        return render(request,'pollster/detail.html',{'question' : question, 'error_message' : "You didnt select a choice"})
    else:
        selected_choice.votes +=1
        selected_choice.save()
        return HttpResponseRedirect(reverse('pollster:results',args=(question.id,)))        

pollster/templates/pollster/base.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<style>

    body{
        background-image: url("/staticfiles/images/PS4.jpg");
        background-repeat: no-repeat, repeat;
        background-size: cover;
    }
</style>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <title>Pollster {% block title %}{% endblock %}</title>
  </head>
  <body>
    {% include 'pollster/navbar.html' %}
    <div class="container">
      <div class="row">
        <div class="col-md-6 m-auto">
          {% block content %}{% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

pollster/templates/pollster/detail.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<style>

.text-center{
         color: #fff;
        }

.lead{
         color: #fff;
         
        }        
</style>

{% extends 'pollster/base.html' %}
{% block content %}
<a class="btn btn-secondary btn-sm mb-3" href="{% url 'pollster:index' %}">Back To Polls</a>
<h1 class="text-center">{{ question.question }}</h1>

{% if error_message %}
<p class="alert alert-danger">
	<strong>{{ error_message }}</strong>
</p>
{% endif %}

<form action="{% url 'pollster:vote' question.id %}" method="post">
	{% csrf_token %} 
	{% for choice in question.choice_set.all %}
		<div class="lead">
			<input
				type="radio"
				name="choice"
				class="form-check-input"
				id="choice{{ forloop.counter }}"
				value="{{ choice.id }}"
			/>
			<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label
			>
		</div>
	{% endfor %}
	<input type="submit" value="Vote" class="btn btn-success btn-lg btn-block mt-4" />
</form>
{% endblock %}

pollster/templates/pollster/index.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<style>

.text-center{
         color: #fff;
        }

.lead{
         color: #fff;
         font-size: 16px;
        }
.scrollbar{
        height: 480px;
        overflow-y: scroll;
        margin-bottom: 5px;
    }

    #style-2::-webkit-scrollbar-track{
        /*-webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);*/
        border-radius: 10px;
        background-color: #dddddb00;
    }

    #style-2::-webkit-scrollbar{
        width: 7px;
        background-color: #dddddb00;
    }

    #style-2::-webkit-scrollbar-thumb{
        border-radius: 10px;
        -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,.3);
        background-color: #396cabb8;
    }                
</style>

{% extends 'pollster/base.html' %}
{% block content %}
    <h1 class="text-center"> Poll Question</h1>
    {% if latest_question_list %}
        {% for question in latest_question_list %}
            <div class="class-mb-3 ">
                <div class="card-body">
                    <p class="lead"><b>{{question.question}}</b></p>
                    <a href="{% url 'pollster:detail' question.id %}" class="btn btn-primary
                    btn-sm">Vote now</a>
                    <a href="{% url 'pollster:results' question.id %}" class="btn btn-primary
                    btn-sm">Results</a>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p> No polls available </p>
    {% endif %}                    


{% endblock %}    

pollster/templates/pollster/navbar.html
<nav class="navbar navbar-dark mb-4" style="background-color:black;">
	<div class="container">
		<a class="navbar-brand" href="{% url 'pollster:index' %}"><b>Pollster</b></a>
		<a class="navbar-brand" href="{% url 'home' %}">Home</a>
	</div>
</nav>

pollster/templates/pollster/result.html
{% extends 'pollster/base.html' %}
{% block content %}
<h1 class="mb-5 text-center">{{ question.question }}</h1>

<ul class="list-group mb-5">
	{% for choice in question.choice_set.all %}
	<li class="list-group-item">
		 {{ choice.choice_text }} <span class="badge badge-success float-right">{{ choice.votes }} vote{{ choice.votes | pluralize }}</span>
	</li>
	{% endfor %}
</ul>

<a class="btn btn-secondary" href="{% url 'pollster:index' %}">Back To Polls</a>
<a class="btn btn-dark" href="{% url 'pollster:detail' question.id %}">Vote again?</a>
{% endblock %}